-- Esse quary é pracriar o banco e para criar as tabelas.

CREATE DATABASE CONTROLE_FINANCEIRO;

USE CONTROLE_FINANCEIRO;

--criando a tabela receitas e suas colunas.
CREATE TABLE RECEITAS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DESCRICAO VARCHAR(60), DATA_RECEBIMENTO DATE, STATUS VARCHAR(60), ORIGEM VARCHAR(60));

--criando a tabela despesas e suas colunas 
CREATE TABLE DESPESAS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DESCRICAO VARCHAR(60), DATA_PAGAMENTO DATE, STATUS VARCHAR(60), ORIGEM VARCHAR(60));

--criando a tabela CONTAS_BANCARIAS E SUAS COLUNAS
CREATE TABLE CONTAS_BANCARIAS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, TIPO VARCHAR(20), BANCO VARCHAR(20), SALDO DECIMAL(6.2));
