
SET @DESCRICAO = 'mother';
SET @VALOR = 182000.10;
SET @DATA_RECEBIMENTO = '2023-03-01';
SET @STATUS = '1';
SET @ORIGEM = 'free';
SET @FK_CONTA = 1;

INSERT INTO RECEITAS (DESCRICAO, DATA_RECEBIMENTO, STATUS, ORIGEM, VALOR, FK_CONTA) VALUES (@DESCRICAO, @DATA_RECEBIMENTO, @STATUS, @ORIGEM,@VALOR,@FK_CONTA);



UPDATE CONTAS_BANCARIAS SET SALDO = @VALOR + SALDO WHERE ID = 1;
