-- adicionando informações na tabela RECEITAS;
INSERT INTO RECEITAS (DESCRICAO, DATA_RECEBIMENTO, STATUS, ORIGEM) VALUES ('CRIACAO DE SITE', '2023-03-03','RECEBIDO','FRELLA');


--adicionando informações na tabela DESPESAS;

INSERT INTO DESPESAS (DESCRICAO, DATA_VENCIMENTO, STATUS, ORIGEM) VALUES ('FINANCEIAMENTO GOL', '2023-03-14','A VENCER','BV');
